######################################################################
# Automatically generated by qmake (3.0) Fri Aug 26 22:56:09 2016
######################################################################

TEMPLATE = app
TARGET = dvo
INCLUDEPATH += . /home/mylxiaoyi/source/ros_catkin.kinetic/install_isolated/include \
               /usr/local/include/vtk-6.1 \
               /usr/local/include/pcl-1.8 \
               /usr/include/eigen3 \
               dvo_benchmark/include \
               dvo_core/include \
               dvo_core/src \
               dvo_ros/include

# Input
HEADERS += dvo_benchmark/include/dvo_benchmark/file_reader.h \
           dvo_benchmark/include/dvo_benchmark/groundtruth.h \
           dvo_benchmark/include/dvo_benchmark/rgbd_pair.h \
           dvo_benchmark/include/dvo_benchmark/tools.h \
           dvo_core/include/dvo/dense_tracking.h \
           dvo_core/src/visualization/bounded_buffer.h \
           dvo_ros/include/dvo_ros/camera_base.h \
           dvo_ros/include/dvo_ros/camera_dense_tracking.h \
           dvo_ros/include/dvo_ros/camera_tracker_nodelet.h \
           dvo_core/include/dvo/core/datatypes.h \
           dvo_core/include/dvo/core/interpolation.h \
           dvo_core/include/dvo/core/intrinsic_matrix.h \
           dvo_core/include/dvo/core/least_squares.h \
           dvo_core/include/dvo/core/math_sse.h \
           dvo_core/include/dvo/core/rgbd_image.h \
           dvo_core/include/dvo/core/surface_pyramid.h \
           dvo_core/include/dvo/core/weight_calculation.h \
           dvo_core/include/dvo/util/fluent_interface.h \
           dvo_core/include/dvo/util/histogram.h \
           dvo_core/include/dvo/util/id_generator.h \
           dvo_core/include/dvo/util/revertable.h \
           dvo_core/include/dvo/util/stopwatch.h \
           dvo_core/include/dvo/visualization/async_point_cloud_builder.h \
           dvo_core/include/dvo/visualization/camera_trajectory_visualizer.h \
           dvo_core/include/dvo/visualization/pcl_camera_trajectory_visualizer.h \
           dvo_core/include/dvo/visualization/point_cloud_aggregator.h \
           dvo_core/include/dvo/visualization/visualizer.h \
           dvo_ros/cfg/cpp/dvo_ros/CameraDenseTrackerConfig.h \
           dvo_ros/include/dvo_ros/util/configtools.h \
           dvo_ros/include/dvo_ros/util/util.h \
           dvo_ros/include/dvo_ros/visualization/ros_camera_trajectory_visualizer.h
SOURCES += dvo_benchmark/src/benchmark.cpp \
           dvo_core/src/dense_tracking.cpp \
           dvo_core/src/dense_tracking_config.cpp \
           dvo_ros/src/camera_base.cpp \
           dvo_ros/src/camera_dense_tracking.cpp \
           dvo_ros/src/camera_tracker_node.cpp \
           dvo_ros/src/camera_tracker_nodelet.cpp \
           dvo_core/src/core/interpolation.cpp \
           dvo_core/src/core/intrinsic_matrix.cpp \
           dvo_core/src/core/least_squares.cpp \
           dvo_core/src/core/math_sse.cpp \
           dvo_core/src/core/rgbd_image.cpp \
           dvo_core/src/core/rgbd_image_sse.cpp \
           dvo_core/src/core/surface_pyramid.cpp \
           dvo_core/src/core/weight_calculation.cpp \
           dvo_core/src/util/histogram.cpp \
           dvo_core/src/util/id_generator.cpp \
           dvo_core/src/visualization/async_point_cloud_builder.cpp \
           dvo_core/src/visualization/camera_trajectory_visualizer.cpp \
           dvo_core/src/visualization/pcl_camera_trajetory_visualizer.cpp \
           dvo_core/src/visualization/point_cloud_aggregator.cpp \
           dvo_core/src/visualization/visualizer.cpp \
           dvo_ros/src/visualization/ros_camera_trajectory_visualizer.cpp

DISTFILES += \
    dvo_benchmark/launch/benchmark.yaml \
    dvo_benchmark/manifest.xml \
    dvo_benchmark/package.xml \
    dvo_core/manifest.xml \
    dvo_core/package.xml \
    dvo_ros/manifest.xml \
    dvo_ros/nodelet_plugins.xml \
    dvo_ros/package.xml \
    sophus/manifest.xml \
    dvo_benchmark/launch/benchmark.launch \
    dvo_benchmark/LICENSE \
    dvo_benchmark/mainpage.dox \
    dvo_core/LICENSE \
    dvo_core/mainpage.dox \
    dvo_ros/docs/CameraDenseTrackerConfig-usage.dox \
    dvo_ros/docs/CameraDenseTrackerConfig.dox \
    dvo_ros/docs/CameraDenseTrackerConfig.wikidoc \
    dvo_ros/launch/quickstart.launch \
    dvo_ros/launch/rviz.vcg \
    dvo_ros/LICENSE \
    dvo_ros/mainpage.dox \
    dvo_benchmark/CMakeLists.txt \
    dvo_core/CMakeLists.txt \
    dvo_ros/CMakeLists.txt \
    README.md \
    dvo_ros/cfg/dvo.cfg \
    dvo_ros/src/dvo_ros/cfg/__init__.py \
    dvo_ros/src/dvo_ros/cfg/CameraDenseTrackerConfig.py \
    dvo_ros/src/dvo_ros/__init__.py
